### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by DeLaphante** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#1]
Can you make the binary MicrosoftWebDriver.exe instead of msedgedriver.exe please.

It will make it easier to use

**Comment by leandrodotec** [comment]
@DeLaphante, this is the official filename when it is downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by Piedone** [comment]
However, `EdgeDriver` indeed looks for it as MicrosoftWebDriver.exe so that would be a better default. Otherwise you can overcome this when constructing the driver:

```
new EdgeDriver( EdgeDriverService.CreateDefaultService(".", "msedgedriver.exe"));
```

Thank you for this project BTW! I was really delighted that following what the Chrome, FF and IE drivers are doing you've added a `PublishMsEdgeDriver` build property. This is necessary so we don't have to add the NuGet to child projects too when they depend on some testing framework parent project that includes this package.
