### ISSUE TITLE
No  Nuget package available for current browser version

### ISSUE THREAD

**Issue by HoneyBeeJack** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#36]
Current browser version is 117 but the latest nuget packages is 115.

What is the process here to have package version which matches the latest browser version?

**Comment by Napoleon10** [comment]
Hello HoneyBeeJack, 
I have raised this issue - #34 
The process is that we are waiting for a response from the Dev for this driver.  
You might find this an interesting read. 
https://www.selenium.dev/documentation/selenium_manager/

Personally, I am using SpecFlow in Visual Studio for automation; and, although you can download the latest driver version, /driver path/selenium-manager --browser edge -- debug - you need the actual Nuget Package I have found, because I receive an error when I perform a 'rebuild.'
Hope this helps! Cheers...

**Comment by YogeshJayaseelan** [comment]
@Napoleon10 Im using NUnit in Visual studio and do you have any idea how to get the latest edge version

**Comment by Napoleon10** [comment]
I have for the time being changed to Chrome. If you are using EdgeOptions with various configurations, like 'AddArguments' method, you can just use ChromeOptions instead. Hope this is of some use, otherwise keep an eye on the issue I raised #34

**Comment by YogeshJayaseelan** [comment]
@Napoleon10 @HoneyBeeJack - Finally i could see the latest version of MS Edge in the Nuget Package Manager. But, this is time its too late for the latest version!!

**Comment by Napoleon10** [comment]
Hi @HoneyBeeJack , you are going to want to close this issue off, see #34 , cheers John.

**Comment by HoneyBeeJack** [comment]
Hopefully next versions will be provided on time  ;)
